// kjsgen:start default
// Generated by KubeJS Generator (kjsgen) from project 'default'.
// Everything inside this marker block is overwritten on re-export; edits outside it are kept.
ServerEvents.recipes(event => {
  // caupona:stew_pot
  event.remove({ output: 'caupona:stew_pot' })
  event.shaped('caupona:stew_pot', ['A A', 'A A', 'AAA'], {
      A: '#c:plates/iron'
    }).id('neopona:stew_pot')
  // 4x minecraft:bowl
  event.remove({ output: 'minecraft:bowl' })
  event.shaped('4x minecraft:bowl', ['A A', ' A '], {
      A: '#c:plates/iron'
    })
})
// kjsgen:end default
