[fiahi-common-config]
	#Which foods will never be frozen.
	NEVER_FROZEN_FOODS = ["minecraft:dried_kelp"]
	#Which foods will never be rotten.
	NEVER_ROTTEN_FOODS = ["minecraft:golden_apple", "minecraft:enchanted_golden_apple", "minecraft:golden_carrot", "emeraldcraft:golden_peach", "emeraldcraft:agate_apple", "emeraldcraft:jade_apple"]
	#If false, foods will never be frozen.
	ENABLE_FROZEN = true
	#If false, foods will never be rotten.
	ENABLE_ROTTEN = true
	#How many ticks after a single check will it try again to modify the temperature of the food.
	# Default: 120
	# Range: 1 ~ 24000
	TEMPERATURE_CHECKER_INTERVAL = 120
	#When trying to modify the temperature of the food each time, how many difference will be applied.
	# Default: 10
	# Range: 1 ~ 100
	TEMPERATURE_BALANCE_RATE = 10
	#How fast will a food item get frozen. The bigger, the faster.
	# Default: 1.0
	# Range: 0.01 ~ 100.0
	FROZEN_SPEED_MULTIPLIER = 1.0
	#How fast will a food item get rotten. The bigger, the faster.
	# Default: 0.75
	# Range: 0.01 ~ 100.0
	ROTTEN_SPEED_MULTIPLIER = 0.75
	#A whitelist of containers. Food items in these block entities will never be affected by temperature.
	STABLE_TEMPERATURE_CONTAINERS = ["cold_sweat:boiler", "cold_sweat:icebox"]
