#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Aug 18 00:34:19 MDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=World Outline Shader r1.0.zip
