# Debug renderer for last hit information
# Available only in singleplayer/lan worlds
enableHitDebug: false

# Forces player rotation synchronization between server and clients
forceEntityRotationSynchronization: true

# Expands entity hitbox for projectile detection purposes by this amount in all directions
defaultEntityHitboxInflation: 0.2

# Uses less hit traces for explosions to save performance
useExplosionPerformanceMode: false

# Allows interactions (such as healing) with other entities
allowThirdPartyEntityInteractions: true

# Health related configurations
health:
  # Health will be primarily recovered into vital parts
  prioritizeVitalHealing: true

  # Threshold for prioritized vital limb health recovery
  vitalBodyPartHealthTrigger: 0.75

  # Global damage multiplier for all limbs
  globalDamageMultiplier: 1.0

  # Damage multiplier for head
  headDamageMultiplier: 1.0

  # Damage multiplier for body
  bodyDamageMultiplier: 1.0

  # Damage multiplier for stomach
  stomachDamageMultiplier: 1.0

  # Damage multiplier for arms
  armDamageMultiplier: 1.0

  # Damage multiplier for legs
  legDamageMultiplier: 1.0

  # Damage multiplier for animal limbs
  animalDamageMultiplier: 1.0

  # Damage multiplier for all other limbs
  otherDamageMultiplier: 1.0

armor:
  # Defines armor calculation logic with custom health system
  # SIMULATED - modular armor with fully simulated logic such as deflections, blunt damage and so on
  # MODULAR - modular armor - getting entryPoint in head damages only helmet
  # MODULAR_BOOSTED - same as above, but each armor piece has additional protection. Configurable below
  # VANILLA - vanilla armor calculation, full armor is used for any damage calculations
  # Allowed values:
  # - SIMULATED
  # - MODULAR
  # - MODULAR_BOOSTED
  # - VANILLA
  armorSystem: SIMULATED

  # Additional armor protection per armor piece when using MODULAR_BOOSTED armor system
  modularBoostedArmorMultiplier: 2.5

  # Configure which limbs are covered by specific armor pieces. Does nothing when using VANILLA armor system
  limbArmorProtectionAreas:
    # Allowed values:
    # - MAINHAND
    # - OFFHAND
    # - FEET
    # - LEGS
    # - CHEST
    # - HEAD
    # - BODY
    head:
      - HEAD

    # Allowed values:
    # - MAINHAND
    # - OFFHAND
    # - FEET
    # - LEGS
    # - CHEST
    # - HEAD
    # - BODY
    chest:
      - CHEST

    # Allowed values:
    # - MAINHAND
    # - OFFHAND
    # - FEET
    # - LEGS
    # - CHEST
    # - HEAD
    # - BODY
    stomach:
      - CHEST

    # Allowed values:
    # - MAINHAND
    # - OFFHAND
    # - FEET
    # - LEGS
    # - CHEST
    # - HEAD
    # - BODY
    arms:

    # Allowed values:
    # - MAINHAND
    # - OFFHAND
    # - FEET
    # - LEGS
    # - CHEST
    # - HEAD
    # - BODY
    legs:
      - LEGS
      - FEET

    # Allowed values:
    # - MAINHAND
    # - OFFHAND
    # - FEET
    # - LEGS
    # - CHEST
    # - HEAD
    # - BODY
    animalBody:
      - BODY

    # Allowed values:
    # - MAINHAND
    # - OFFHAND
    # - FEET
    # - LEGS
    # - CHEST
    # - HEAD
    # - BODY
    other:

# Blood/Unconscious system related configurations
bloodSystem:
  # Enables blood system simulation, unconscious player state
  useBloodSystem: true

  # Enables blood level display in health UI
  showBloodLevel: false

  # Enables blood type display in health UI
  showBloodType: true

  # Defines handling of unconscious bleed out stage when the affected player has too low blood level to wake up on their own
  # When disabled, bleed out damage will be applied immediately after losing ability to wake up
  # Allowed values:
  # - ALLOW
  # - ONLY_MULTIPLAYER
  # - DISABLE
  bleedOutUnconsciousness: ALLOW

  # Specifies when entities can target unconscious players
  # ALWAYS - unconscious players will always be attacked
  # IGNORE_RESCUE - unconscious players will be attacked as long as they're not in rescue mode
  # NEVER - unconscious players will never be attacked
  # Allowed values:
  # - ALWAYS
  # - IGNORE_RESCUE
  # - NEVER
  unconsciousEntityTargeting: NEVER

  # Chance specifying if you can enter unconscious state instead of dying so that you may be rescued by your friends
  unconsciousOnDeathChance: 1.0

  # Will prevent entering unconscious state on death if your head limb is dead too
  unconsciousOnHeadDeathChance: 1.0

  # Rescue waiting period before dying while in death unconscious state
  rescueWaitDuration: 3000

  # Unconscious duration interval on unconsciousness due to blood loss
  unconsciousOnBloodLoss:
    minDuration: 5

    maxDuration: 10

  unconsciousHeldItemDropChance: 0.6

  unconsciousSoundVolumeScale: 0.2

  unconsciousSoundPitchScale: 0.7

  # Allowed values:
  # - STATIC
  # - BLINKING
  unconsciousOverlayType: BLINKING

  shockPerHpLoss: 0.04

  shockPerLimbLoss: 0.25

  shockPerFracture: 0.1

statusEffects:
  # Enables entryPoint effects such as bleeds, fractures and other effects
  enableStatusEffects: true

  # Base chance for getting any type of bleed from '#medsystem:bleed_causing' damage type
  bleedChance: 0.025

  # Configure max bleed duration for effect stacking
  # Set to 0 to disable all limits
  maxBleedDuration: 0

  # Bleed chance multiplier for items from '#medsystem:sharp_tools' tag - swords, spears, axes
  sharpToolBleedMultiplier: 5.0

  # Base chance for getting fracture from '#medsystem:fracture_causing' damage type
  fractureChance: 0.03

  # Default duration of fracture status effect
  # -1 means infinite duration
  fractureDuration: -1

  # Configure max fracture duration for effect stacking
  # Set to 0 to disable all limits
  maxFractureDuration: 0

  # How long it will take for fractures to heal after applying splints
  fractureRecoveryTime: 6000

  # How long it will take for fractures to heal after applying bandages
  fractureRecoveryTimeBandage: 18000

  # Fracture chance multiplier for items from '#medsystem:blunt_tools' tag - shovels, pickaxes, hoes and mace
  bluntToolFractureMultiplier: 5.0

  # Allows scaling of injury recovery status effects when getting the effect repeatedly
  allowInjuryRecoveryScaling: true

  # Configure max injury recovery duration for effect stacking
  # Set to 0 to disable all limits
  maxInjuryRecoveryDuration: 0

  bleedConfiguration:
    lightBleed:
      weight: 50

      minDamageThreshold: 1.5

      # Default duration of bleeding status effect
      # -1 means infinite duration
      bleedDuration: -1

      bleedInterval: 60

      bleedAmount: 0.005

      woundDuration: 0

      decalCount: 1

    moderateBleed:
      weight: 30

      minDamageThreshold: 2.5

      # Default duration of bleeding status effect
      # -1 means infinite duration
      bleedDuration: -1

      bleedInterval: 45

      bleedAmount: 0.01

      woundDuration: 0

      decalCount: 2

    heavyBleed:
      weight: 15

      minDamageThreshold: 3.0

      # Default duration of bleeding status effect
      # -1 means infinite duration
      bleedDuration: -1

      bleedInterval: 30

      bleedAmount: 0.025

      woundDuration: 6000

      decalCount: 5

    criticalBleed:
      weight: 5

      minDamageThreshold: 5.0

      # Default duration of bleeding status effect
      # -1 means infinite duration
      bleedDuration: -1

      bleedInterval: 10

      bleedAmount: 0.06

      woundDuration: 12000

      decalCount: 8

bloodDecals:
  # Toggles all blood decals
  enableBloodDecals: true

  # Forces all blood decals to be have specific color - configure in the option below
  forceBloodDecalColor: false

  bloodDecalColor: #B20000

  bloodDecalLifetime: 1200

  # Blood decal rendering scale
  bloodDecalScale: 0.15

  # Lifetime percentage at which decals will start to fade out
  bloodDecalFadeOutAt: 0.25

  # How much damage entity needs to receive in order for decal to appear
  damageDecalScale: 3.0

  # Maximum amount of decals which can appear when damaging entities
  # Set to 0 to disable damage decals
  maxDamageDecalsPerHit: 8

  # How much motion is applied to decals on received damage
  damageMotionScale: 0.25

  # How much motion is applied to decals on received damage from projectiles
  projectileDamageMotionScale: 0.6

