#.
#Config version check, values below 0 will disable config version checker
# Default: 5
# Range: > -2147483648
configVersion = 5

#.
#Cold Sweat configuration values
[cold_sweat]
	#.
	#.
	#Factor used to calculate the heat that players receive, in ºMC per 100ºC
	# Default: 0.03999999910593033
	# Range: 0.0 ~ 3.4028234663852886E38
	coldSweatTempScalar = 0.03999999910593033
	#.
	#Factor used to calculate the maximum range at which players receive heat, in blocks per 100ºC
	# Default: 0.5
	# Range: 0.0 ~ 3.4028234663852886E38
	coldSweatRangeScalar = 0.5

#.
#Things related to kinetic and electrokinetic devices
[kinetics]
	#.
	#.
	#Cooling multiplier applied to devices in the air stream (multiplied by rotational speed)
	# Default: 0.009999999776482582
	# Range: 0.0 ~ 3.4028234663852886E38
	encasedFanCooling = 0.009999999776482582
	#.
	#Controls the torque force calculated from stress impact of machines (used by generators and motors)
	# Default: 15.0
	# Range: 0.0 ~ 3.4028234663852886E38
	torqueForStress = 15.0
	#.
	#How much lightning rod linear velocity is needed to reach the maximum lightning attractor firing rate
	# Default: 0.05000000074505806
	# Range: 0.0 ~ 3.4028234663852886E38
	lightningAttractorSpeedFactor = 0.05000000074505806
	#.
	#How many sail blocks are needed to reach the maximum lightning attractor firing rate
	# Default: 0.125
	# Range: 0.0 ~ 3.4028234663852886E38
	lightningAttractorSailFactor = 0.125
	#.
	#How often can the lightning attractor fire
	# Default: 0.05000000074505806
	# Range: 0.0 ~ 3.4028234663852886E38
	lightningAttractorMaxFrequency = 0.05000000074505806

	#.
	#Rotor control factors
	[kinetics.generatorControl]
		#.
		#.
		#Factor to scale the Proportional factorof the Rotor's force calculation
		# Default: 0.8500000238418579
		# Range: 0.0 ~ 3.4028234663852886E38
		rotorKp = 0.8500000238418579
		#.
		#Factor to scale the Differential factor of the Rotor's force calculation
		# Default: 0.0020000000949949026
		# Range: 0.0 ~ 3.4028234663852886E38
		rotorKd = 0.0020000000949949026
		#.
		#Maximum rotation speed of a rotor
		# Default: 272
		# Range: > 0
		rotorRPMMax = 272
		#.
		#Maximum length of a rotor assembly
		# Default: 8
		# Range: > 3
		rotorAssemblyMaxSize = 8
		#.
		#Force of friction applied for each segment of the rotor assembly
		# Default: 0.25
		# Range: 0.0 ~ 3.4028234663852886E38
		rotorSegmentFriction = 0.25
		#.
		# Default: 0.5
		# Range: 0.0 ~ 3.4028234663852886E38
		generatorRotorInertia = 0.5
		#.
		# Default: 0.5
		# Range: 0.0 ~ 3.4028234663852886E38
		generatorInductionRotorInertia = 0.5
		#.
		# Default: 2.0
		# Range: 0.0 ~ 3.4028234663852886E38
		generatorLargeInductionRotorInertia = 2.0
		#.
		# Default: 0.10000000149011612
		# Range: 0.0 ~ 3.4028234663852886E38
		generatorCommutatorInertia = 0.10000000149011612
		#.
		# Default: 0.10000000149011612
		# Range: 0.0 ~ 3.4028234663852886E38
		generatorClutchInertia = 0.10000000149011612
		#.
		#Controls the conversion rate between RPM and voltage generated by windings
		# Default: 5.0
		# Range: 0.10000000149011612 ~ 3.4028234663852886E38
		windingCoilConstant = 5.0
		#.
		#Current required for maximum field strength of the generator's field windings
		# Default: 2.0
		# Range: 0.0 ~ 3.4028234663852886E38
		fieldSaturationCurrent = 2.0
		#.
		#Allow generator rotors to deal damage to entities
		dangerousGenerators = true

		#.
		#Fine tune the kinetic stats of individual components
		[kinetics.stressValues.v3]

			#.
			#.
			#[in Stress Units]
			#Configure the individual stress impact of mechanical blocks. Note that this cost is doubled for every speed increase it receives.
			[kinetics.stressValues.v3.impact]
				generator_clutch = 32.0
				hv_breaker = 2.0
				generator_induction_rotor = 32.0
				hv_switch = 2.0
				rheostat = 0.0
				generator_vertical_commutator = 8.0
				plotter = 2.0
				punch_card_reader = 2.0
				variac = 0.0
				generator_commutator = 8.0
				generator_large_induction_rotor = 128.0

			#.
			#[in Stress Units]
			#Configure how much stress a source can accommodate for.
			[kinetics.stressValues.v3.capacity]
				servo = 32.0
				constant_speed_motor = 64.0
				electric_motor = 64.0

#.
#Recipe configuration values
[recipes]
	#.
	#.
	#Chance for lightning strike to turn a single iron ingot into a magnet
	# Default: 0.05000000074505806
	# Range: 0.0 ~ 1.0
	lightningMagnetizationChance = 0.05000000074505806

#.
#Equipment configuration values
[equipment]
	#.
	#.
	#Energy used by Electro-Zapper per shot
	# Default: 500
	# Range: > 1
	electroZapperEnergyPerShot = 500
	#.
	#Energy used by Electro-Baton per hit
	# Default: 250
	# Range: > 1
	electroBatonEnergyPerShot = 250
	#.
	#Energy used by the tool for each block mined
	# Default: 25
	# Range: > 1
	portableDrillEnergyPerUse = 25
	#.
	#Base mining speed of the Portable Drill
	# Default: 6.0
	# Range: 0.0 ~ 3.4028234663852886E38
	drillMineSpeedBase = 6.0
	#.
	#Top mining speed of the Portable Drill when used continuously
	# Default: 16.0
	# Range: 0.0 ~ 3.4028234663852886E38
	drillMineSpeedBulk = 16.0
	#.
	#Energy used by the tool for each block mined
	# Default: 100
	# Range: > 1
	portableSawEnergyPerUse = 100
	#.
	#Mining speed of the Portable Saw
	# Default: 6.0
	# Range: 0.0 ~ 3.4028234663852886E38
	sawMineSpeedBase = 6.0
	#.
	#Portable Battery energy capacity before enchants
	# Default: 20000
	# Range: > 1
	portableBatteryBaseCapacity = 20000
	#.
	#Portable Battery energy capacity increase per level of Capacity enchant
	# Default: 20000
	# Range: > 1
	portableBatteryEnchantCapacity = 20000
	#.
	#Max multimeter distance
	# Default: 5.0
	# Range: 1.0 ~ 3.4028234663852886E38
	multimeterDistance = 5.0
	#.
	#Max multimeter voltage
	# Default: 500.0
	# Range: 1.0 ~ 3.4028234663852886E38
	multimeterVoltage = 500.0
	#.
	#Max multimeter current
	# Default: 50.0
	# Range: 1.0 ~ 3.4028234663852886E38
	multimeterCurrent = 50.0

#.
#All things related to purely electrical devices
[electricity]
	#.
	#.
	#Controls the behaviour of overheated devices. If false, instead of exploding, they break without dropping items.
	explosiveDeconstruction = true
	#.
	#Controls the overheat mechanic. Devices which are overheated, break.
	overheating = true
	#.
	#Controls the overheat mechanic for wires. Wires will burn if they overheat.
	wireOverheating = true
	#.
	#Multiplier of the base fan bulk processing time applied to items processed with the heating coil (lower value means faster processing)
	# Default: 0.75
	# Range: 0.0 ~ 3.4028234663852886E38
	heaterFanProcessingSpeedMultiplier = 0.75
	#.
	#Radius of the area affected by growth lamp effect
	# Default: 2
	# Range: > 1
	growthLampRadius = 2
	#.
	#Chance value for the growth lamp to tick a random block in its area (lower value = higher chance), this value is divided by lamp's power level
	# Default: 50
	# Range: > 0
	growthLampChance = 50
	#.
	#Vary motor resistance based on stress consumption
	motorDynamicResistance = true
	#.
	#Conversion rate of volts to Forge Energy (controls buffer size and max transfer rate)
	# Default: 2.0
	# Range: 0.0 ~ 3.4028234663852886E38
	forgeEnergyPerVolt = 2.0
	#.
	#Conversion rate of watts to Forge Energy (controls the actual energy cost of a unit of FE)
	# Default: 10.0
	# Range: 0.0 ~ 3.4028234663852886E38
	forgeEnergyPerWatt = 10.0
	#.
	#Maximum power generated by a device connector when it is connected to a 'Create: The Factory Must Grow' electrical network
	# Default: 10000
	# Range: > 0
	TFMGConnectorPower = 10000
	#.
	#Capacity of the acid battery, measured in watt-hours
	# Default: 120.0
	# Range: 0.0 ~ 3.4028234663852886E38
	acidBatteryCapacity = 120.0
	#.
	#Initial charge of the acid battery
	# Default: 0.8999999761581421
	# Range: 0.0 ~ 1.0
	acidBatteryInitialCharge = 0.8999999761581421
	#.
	#Acid battery internal resistance when fully charged, measured in Ohms
	# Default: 0.10000000149011612
	# Range: 0.0010000000474974513 ~ 100.0
	acidBatteryFullChargeInternalResistance = 0.10000000149011612
	#.
	#Multiplies the mutual inductance of transformers to get a resistance. Bigger values make transformers use less electricity.
	# Default: 10.0
	# Range: 1.0 ~ 3.4028234663852886E38
	transformerMutualInductanceMultiplier = 10.0
	#.
	#Percent of the turn-on current required for on state to be kept by relays and conductors
	# Default: 0.8999999761581421
	# Range: 0.009999999776482582 ~ 0.9900000095367432
	holdingCurrentPercent = 0.8999999761581421
	#.
	#Minimum blocks needed for a grounding rod to work
	# Default: 10
	# Range: > 0
	groundingMinimumBlocks = 10
	#.
	#Maximum conductive blocks needed for a grounding rod to reach its lowest resistance
	# Default: 64
	# Range: > 0
	groundingMaximumBlocks = 64
	#.
	#Highest resistance of the grounding rod
	# Default: 5000.0
	# Range: 0.0010000000474974513 ~ 3.4028234663852886E38
	groundingHighestResistance = 5000.0
	#.
	#Lowest resistance of the grounding rod
	# Default: 1.0
	# Range: 0.0010000000474974513 ~ 3.4028234663852886E38
	groundingLowestResistance = 1.0
	#.
	#Maximum block height of the carbon pile structure
	# Default: 5
	# Range: > 1
	carbonPileMaxHeight = 5
	#.
	#Carbon pile "gain", controls how much the coil current affects the resistance
	# Default: 10.0
	# Range: 0.0 ~ 3.4028234663852886E38
	carbonPileGain = 10.0
	#.
	#Al parameter of small transformer core (affects resistance per turn)
	# Default: 1.5
	# Range: 0.0 ~ 3.4028234663852886E38
	smallCoreAl = 1.5
	#.
	#K parameter of small transformer core (affects stray resistance)
	# Default: 0.9998999834060669
	# Range: 0.0 ~ 1.0
	smallCoreK = 0.9998999834060669
	#.
	#Al parameter of medium transformer core (affects resistance per turn)
	# Default: 10.0
	# Range: 0.0 ~ 3.4028234663852886E38
	mediumCoreAl = 10.0
	#.
	#K parameter of medium transformer core (affects stray resistance)
	# Default: 0.9999899864196777
	# Range: 0.0 ~ 1.0
	mediumCoreK = 0.9999899864196777
	#.
	#Minimum current flowing through a cut wire that will start causing damage
	# Default: 0.20000000298023224
	# Range: 0.0 ~ 3.4028234663852886E38
	wireCutDamageCurrentThreshold = 0.20000000298023224
	#.
	#Enable circuit forming interaction for players in creative mode
	creativePlayerShortsWires = false
	#.
	#Minimum current flowing through an entity for it to receive damage
	# Default: 0.10000000149011612
	# Range: 0.0 ~ 3.4028234663852886E38
	entityCurrentDamageThreshold = 0.10000000149011612
	#.
	#Resistance of entities when they are shorting wires
	# Default: 5000.0
	# Range: 0.0 ~ 3.4028234663852886E38
	entityResistance = 5000.0
	#.
	#Enables entities to form circuits when touching wires
	entityWireInteractions = true
	#.
	#Maximum block range of the factory light projected light blocks
	# Default: 16
	# Range: > 0
	factoryLightProjectionRange = 16
	#.
	#Control whether the plotter records voltage values when networks are not converged
	plotterRecordNonconvergence = false
	#.
	#Block range of the electric pump
	# Default: 24
	# Range: > 0
	electricPumpRange = 24
	#.
	#Controls how much power is needed to run the pump at a given speed
	# Default: 2.134999990463257
	# Range: 0.0 ~ 3.4028234663852886E38
	electricPumpPower = 2.134999990463257
	#.
	#Maximum speed the pump can run at (can be above the Create's speed limit)
	# Default: 256.0
	# Range: 0.0 ~ 3.4028234663852886E38
	electricPumpMaxSpeed = 256.0
	#.
	#Maximum value of the FE Inverter control pin voltage
	# Default: 20.0
	# Range: 0.0 ~ 3.4028234663852886E38
	feInverterControlVoltage = 20.0
	#.
	#Capacitance of the FE Inverter control pin
	# Default: 9.999999747378752E-5
	# Range: 0.0 ~ 1.0
	feInverterControlCapacitance = 9.999999747378752E-5
	#.
	#Controls the FE buffer size, and with it, the maximum generated voltage
	# Default: 20000
	# Range: > 0
	feInverterBufferSize = 20000
	#.
	#Target open circuit voltage for the solar panels
	# Default: 26.399999618530273
	# Range: 0.0 ~ 100.0
	solarPanelVocTarget = 26.399999618530273
	#.
	#Controls the amount of cells in the solar panel (Should be left at 48 if your not trying to imitate a real panel)
	# Default: 48
	# Range: 0 ~ 100
	solarPanelCellCount = 48
	#.
	#Target short circuit current for the solar panels
	# Default: 3.299999952316284
	# Range: 0.0 ~ 100.0
	solarPanelIscTarget = 3.299999952316284
	#.
	#Controls the voltage part of the max power point (should be around 80% of the Voc)
	# Default: 21.1200008392334
	# Range: 0.0 ~ 100.0
	solarPanelVmpTarget = 21.1200008392334
	#.
	#Controls the current part of the max power point, (should be around 92% of the Isc)
	# Default: 3.0360000133514404
	# Range: 0.0 ~ 100.0
	solarPanelImpTarget = 3.0360000133514404
	#.
	#This is the Nominal Operating Cell Temp of the solar cells in the panel
	# Default: 45
	# Range: 0 ~ 100
	solarPanelNOCT = 45
	#.
	#Controls maximum number of solar panels in a single multiblock
	# Default: 25
	# Range: > 1
	solarPanelMaxSize = 25
	#.
	#RPM required to cleanly turn off a HV switch for a given current flowing through it
	# Default: 1.0
	# Range: 0.0 ~ 3.4028234663852886E38
	hvSwitchSparkExtinguishRPMFactor = 1.0
	#.
	#Minimum current for a HV switch spark to continue existing
	# Default: 0.10000000149011612
	# Range: 0.0 ~ 3.4028234663852886E38
	hvSwitchSparkMinimumCurrent = 0.10000000149011612
	#.
	#Voltage required to spark when the switch is turning on, scales with contact distance
	# Default: 1000.0
	# Range: 0.0 ~ 3.4028234663852886E38
	hvSwitchSparkPotentialFactor = 1000.0

	#.
	#Things related to how the simulation is handled (probably shouldn't be altered unless you know what you are doing)
	[electricity.solver]
		#.
		#.
		#Threshold resistance for a transmission line to be able to split the grid into island networks. Lines with resistance above this value have a propagation delay of roughly 1 tick, and can improve performance by simulating small segments of the grid separately.
		# Default: 0.20000000298023224
		# Range: 0.0 ~ 3.4028234663852886E38
		transmissionLineThreshold = 0.20000000298023224
		#.
		#Experimental! Allows transmission lines to split large grid into smaller networks. This option should improve performance for large grids but it will result in transmission lines having a propagation delay and capacitance.
		splittingTransmissionLines = false
		#.
		#Allows transformers to split the grid. This option should improve performance but it will result in transformers having some capacitance and delay.
		splittingsTransformers = false
		#.
		#Maximum solver iterations for networks without dynamic residuals
		# Default: 200
		# Range: > -2147483648
		solverSimpleMaxIterations = 200
		#.
		#Maximum solver iterations for networks with dynamic residuals
		# Default: 200
		# Range: > -2147483648
		solverComplexMaxIterations = 200
		#.
		#Absolute stopping criterion
		# Default: 1.0000000116860974E-7
		# Range: 0.0 ~ 3.4028234663852886E38
		solverAbsolutePrecision = 1.0000000116860974E-7
		#.
		#Relative stopping criterion
		# Default: 9.9999998245167E-15
		# Range: 0.0 ~ 3.4028234663852886E38
		solverRelativePrecision = 9.9999998245167E-15
		#.
		#Minimum accepted precision
		# Default: 9.999999974752427E-7
		# Range: 0.0 ~ 3.4028234663852886E38
		solverAbsoluteMinimumPrecision = 9.999999974752427E-7
		#.
		#Maximum alpha value when performing iteration solution fitting (x1 = x0 * alpha + x1 * (1 - alpha))
		# Default: 0.9900000095367432
		# Range: 0.0 ~ 1.0
		solverMaxSearchAlpha = 0.9900000095367432
		#.
		#BJT inter-iteration voltage change smoothing multiplier
		# Default: 0.5
		# Range: 0.0 ~ 1.0
		bjtLimAlpha = 0.5
		#.
		#Diode inter-iteration voltage change smoothing multiplier
		# Default: 0.02500000037252903
		# Range: 0.0 ~ 1.0
		diodeLimAlpha = 0.02500000037252903
		#.
		#Triode inter-iteration voltage change smoothing multiplier
		# Default: 0.5
		# Range: 0.0 ~ 1.0
		triodeLimAnode = 0.5
		#.
		#Triode inter-iteration voltage change smoothing multiplier
		# Default: 0.5
		# Range: 0.0 ~ 1.0
		triodeLimCathode = 0.5
		#.
		#Triode inter-iteration voltage change smoothing multiplier
		# Default: 0.5
		# Range: 0.0 ~ 1.0
		triodeLimGrid = 0.5
		#.
		seriesWireOptimization = false
		#.
		#Experimental! This option enables all electrical networks to tick multiple times per world tick. This allows for better simulation precision when reactive components are involved but can have a significant impact on performance.
		# Default: 1
		# Range: > 1
		multiTicks = 1
		#.
		#Solver MNA backend. The native backend can provide platform-specific acceleration which usually improves performance, however it isn't portable and needs a special binary which might not be available for all platforms. Java backend is portable and always available as fallback.
		#Allowed Values: JAVA, NATIVE
		solverBackend = "NATIVE"

	#.
	#Resistance values for all devices
	[electricity.resistance-v3]

		#.
		#.
		#[in Ohms]
		#Configure the individual resistances of electrical blocks
		[electricity.resistance-v3.resistance]
			portable_battery = 25.0
			heating_coil = 25.0
			current_gauge = 0.05000000074505806
			lv_switch = 0.15
			carbon_pile = 20.0
			circuit_design_table = 480.0
			electromagnet = 15.0
			electric_motor = 25.6
			mv_switch = 0.05
			carbon_pile_coil = 50.0
			fuse_holder = 0.2
			hv_breaker = 0.1
			generator_induction_rotor = 0.5
			winding = 7.5
			electric_fan = 20.0
			lv_button = 0.15
			hv_switch = 0.1
			punch_card_reader = 1.0
			basin_heater = 10.0
			constant_speed_motor = 25.6
			electric_pump = 480.0
			generator_large_induction_rotor = 1.0
			alarm_bell = 20.0

			[electricity.resistance-v3.resistance.redstone_converter]
				min = 5.0
				max = 1000.0

			[electricity.resistance-v3.resistance.crt]
				coils = 40.0
				heater = 12.0

			[electricity.resistance-v3.resistance.voltage_gauge]
				range_2v = 20000.0
				range_200v = 2000000.0
				range_2kv = 2.0E7
				range_20v = 200000.0

			[electricity.resistance-v3.resistance.power_gauge]
				shunt_range_2kw = 2.0E7
				shunt_range_200w = 2000000.0
				shunt_range_20w = 200000.0
				series = 0.05000000074505806
				shunt_range_20kw = 2.0E7

			[electricity.resistance-v3.resistance.energy_meter]
				series = 0.02500000037252903
				shunt = 2000000.0

			[electricity.resistance-v3.resistance.servo]
				idle = 64.0
				on = 12.8

			[electricity.resistance-v3.resistance.contactor]
				switch = 0.05
				coil = 12.0

	#.
	#Thermal properties for all devices
	[electricity.thermal-v1]

		#.
		#.
		#Configures the amount of energy needed to raise the temperature of the device (this allows for higher temporary loads)
		[electricity.thermal-v1.mass]
			portable_battery = 1.0
			contactor = 2.0
			heating_coil = 1.0
			current_gauge = 2.0
			rheostat = 4.0
			battery = 1.5
			power_resistor = 2.0
			lv_switch = 0.5
			variac = 4.0
			carbon_pile = 2.0
			circuit_design_table = 0.5
			electromagnet = 4.0
			transformer_small = 4.0
			mv_switch = 1.0
			carbon_pile_coil = 2.0
			crt = 3.0
			hv_breaker = 2.0
			redstone_converter = 0.75
			lv_button = 0.5
			winding = 1.5
			hv_switch = 5.0
			punch_card_reader = 0.20000000298023224
			nether_transformer = 16.0
			power_gauge = 2.0
			transformer_medium = 16.0
			alarm_bell = 1.5
			energy_meter = 2.0

		#.
		#[in Watts]
		#Configures the maximum power dissipated by the device
		[electricity.thermal-v1.power]
			portable_battery = 100.0
			contactor = 252.8
			heating_coil = 60.0
			current_gauge = 35.0
			rheostat = 1000.0
			battery = 100.0
			power_resistor = 1000.0
			lv_switch = 38.4
			variac = 1000.0
			carbon_pile = 1000.0
			circuit_design_table = 50.0
			electromagnet = 1500.0
			transformer_small = 1000.0
			mv_switch = 51.2
			carbon_pile_coil = 100.0
			crt = 100.0
			hv_breaker = 102.4
			redstone_converter = 50.0
			lv_button = 38.4
			winding = 200.0
			hv_switch = 1000.0
			punch_card_reader = 10.0
			nether_transformer = 4000.0
			power_gauge = 35.0
			transformer_medium = 4000.0
			alarm_bell = 50.0
			energy_meter = 100.0
