#.
#Amount of red in the CRT screen glow
# Default: 64
# Range: 0 ~ 255
crtRed = 64
#.
#Amount of green in the CRT screen glow
# Default: 4
# Range: 0 ~ 255
crtGreen = 4
#.
#Amount of blue in the CRT screen glow
# Default: 2
# Range: 0 ~ 255
crtBlue = 2
#.
#Controls how many individual points the CRT trace can have (1 point is added per tick)
# Default: 100
# Range: > 10
crtPointCount = 100
#.
#Controls the slope of trace brightness decay (lower value means faster decay)
# Default: 0.02500000037252903
# Range: 0.0 ~ 3.4028234663852886E38
crtTracePersistence = 0.02500000037252903
#.
#Controls the CRT trace thickness
# Default: 0.03125
# Range: 0.0 ~ 3.4028234663852886E38
crtDotSize = 0.03125
#.
#Controls how much the CRT trace falls as it fades. This values shouldn't be too small or it can cause Z fighting
# Default: 9.999999747378752E-5
# Range: 0.0 ~ 3.4028234663852886E38
crtZDepth = 9.999999747378752E-5
#.
#Enable decreased level of detail rendering of far away wires
wireLOD = true
#.
#Multiplier for all humming ambient sounds
# Default: 1.0
# Range: 0.0 ~ 3.4028234663852886E38
hummingSoundMultiplier = 1.0
#.
#Multiplier for generator ambient sound
# Default: 1.0
# Range: 0.0 ~ 3.4028234663852886E38
generatorSoundMultiplier = 1.0

#.
#Circuit editor stuff
["Circuit Design Table"]
	#.
	#.
	#Higher contrast between traces in the circuit editor
	HighContrastTraces = false
	#.
	#Amount of red in traces
	# Default: 255
	# Range: 0 ~ 255
	traceRedTop = 255
	#.
	#Amount of green in traces
	# Default: 255
	# Range: 0 ~ 255
	traceGreenTop = 255
	#.
	#Amount of blue in traces
	# Default: 255
	# Range: 0 ~ 255
	traceBlueTop = 255
	#.
	#Amount of alpha in traces
	# Default: 255
	# Range: 0 ~ 255
	traceAlphaTop = 255
	#.
	#Amount of alpha in traces
	# Default: 128
	# Range: 0 ~ 255
	traceAlphaTopBehind = 128
	#.
	#Amount of red in traces
	# Default: 255
	# Range: 0 ~ 255
	traceRedBottom = 255
	#.
	#Amount of green in traces
	# Default: 255
	# Range: 0 ~ 255
	traceGreenBottom = 255
	#.
	#Amount of blue in traces
	# Default: 255
	# Range: 0 ~ 255
	traceBlueBottom = 255
	#.
	#Amount of alpha in traces on the back
	# Default: 255
	# Range: 0 ~ 255
	traceAlphaBottom = 255
	#.
	#Amount of alpha in traces on the back
	# Default: 128
	# Range: 0 ~ 255
	traceAlphaBottomBehind = 128
