# Configurations related to skill system
skillSystemConfig:
  # Enables skill system
  skillSystemEnabled: true

  # Allows you to lose skill experience (but not levels)
  enableSkillExperienceLoss: true

  # Allows you to lose skill levels
  enableSkillLevelLoss: true

  # Allows you to adjust skill leveling speed
  globalSkillLevelSpeedMultiplier: 1.0

  # Max skill experience to be gained from single trigger - for example killing one mob, collecting one exp orb
  # 0 means no limit
  singleTriggerSkillLevelLimit: 0.0

# Configurations related to weight system
weightConfig:
  # Allows you to toggle weight system
  # Beware as users affected by negative weight effects will be stuck with those effects after disabling
  enableWeightSystem: true

  # Calculates weight based on item storage too - bundles, shulker boxes, ...
  calculateContainerWeight: true

  overweightSpeedReduction: -0.15

  overweightJumpReduction: -0.125

  overweightSafeFallDistanceReduction: -0.4

  overweightStepHeightReduction: -0.15

